spring:
  application:
    name: surl

  datasource:
    url: jdbc:postgresql://localhost:5432/surl
    username: admin
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ee99ed419ddd58872ace1fa9951508a85a95660054b1f1da5f2e36baf1a3e434a0d41550252c0134e651278ee57dfece042a6ea4c600ca0c00693cea30dbaf5c

surl:
  base-url: http://localhost:8080/
  max-attempts: 5
  auth-token-duration: 28800 # 8 hours in seconds